# #############################################################################
# prologue xd Oscillator Makefile
# #############################################################################

MCU_MODEL := STM32F401xC
USER_TARGET_PLATFORM := k_user_target_prologue

include ../project.mk
PKGARCH := $(PROJECT).prlgunit

include ../common.mk
