# #############################################################################
# NTS-1 Oscillator Makefile
# #############################################################################

MCU_MODEL := STM32F446xE
USER_TARGET_PLATFORM := k_user_target_nutektdigital

include ../project.mk
PKGARCH := $(PROJECT).ntkdigunit

include ../common.mk
